# Generated by Django 4.1.7 on 2023-03-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_creator_conversation_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
