# Generated by Django 4.1.7 on 2023-03-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friend_request_user_buddies_delete_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend_Request',
            new_name='FriendRequest',
        ),
    ]
