# Generated by Django 4.1.7 on 2023-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_friend_request_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debugging_headaches',
            field=models.CharField(default='help', max_length=255),
            preserve_default=False,
        ),
    ]
