# Generated by Django 4.1.7 on 2023-03-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='debugging_headaches',
        ),
    ]
