# Generated by Django 4.1.7 on 2023-03-13 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_debugging_headaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('NB', 'NB'), ('T', 'T'), ('O', 'O')], max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/')),
                ('profile_banner', models.ImageField(blank=True, upload_to='images/')),
                ('biography', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
