# Generated by Django 4.1.7 on 2023-03-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_gym_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
