# Generated by Django 4.1.7 on 2023-03-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_friendrequest_created_at_friendrequest_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
