# Generated by Django 4.1.7 on 2023-03-22 02:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, default=accounts.models.Profile.default_banner, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=accounts.models.Profile.default_profile_pic, upload_to='images/'),
        ),
    ]
