# Generated by Django 4.1.7 on 2023-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, default='defaultbanner_Ar155VZ.png', upload_to='images/'),
        ),
    ]
