# Generated by Django 4.1.7 on 2023-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_profile_profile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coordinates',
            field=models.CharField(blank=True, default='0,0', max_length=255),
        ),
    ]
