# Generated by Django 4.1.7 on 2023-03-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
