# Generated by Django 4.1.7 on 2023-03-13 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0003_alter_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='user_timeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
