# Generated by Django 4.1.7 on 2023-03-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_rename_user_timeline_timeline_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='timeline',
        ),
    ]
