# Generated by Django 4.1.7 on 2023-03-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_remove_story_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='timelines.timeline'),
        ),
    ]
